### ISSUE TITLE
Differentiate Lodash from Underscore

### ISSUE THREAD

**Issue by benthemonkey** [NUDelta/Unravel#1]
Visor incorrectly identifies Shmoop.com as including the library "Underscore", while it in fact uses "Lodash".

One way of differentiating the two is the Lodash property: `_.support`, which Underscore doesn't have.

**Comment by 0x-2a** [comment]
Fixed https://github.com/NUDelta/Visor/commit/705f39d5032f19bcf97863b7988fdfba5e5969bd
